networks:
  web3:
    driver: bridge

services:
#  financial-transactions-backend:
#    image: financial-transactions-backend:latest
#    container_name: financial-transactions-backend
#    ports:
#      - 8085:8085
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://bankdb:5432/bankdb
#      - POSTGRES_USER=${DB_USER:-postgres}
#      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#    depends_on:
#      - authorization-backend
#    networks:
#      - web3

  authorization-backend:
    image: authorization-backend:latest
    container_name: authorization-backend
    ports:
      - 8083:8083
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bankdb:5432/bankdb
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - bankdb
    networks:
      - web3

#  card-backend:
#    image: card-backend:latest
#    container_name: card-backend
#    ports:
#      - 8084:8084
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://bankdb:5432/bankdb
#      - POSTGRES_USER=${DB_USER:-postgres}
#      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#    depends_on:
#      - bankdb
#      - authorization-backend
#    networks:
#      - web3

  bankdb:
    image: postgres:14.9
    container_name: bankdb
    environment:
      - POSTGRES_DB=bankdb
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-sa}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - ./data/db-data:/var/lib/postgresql/data/pgdata
    networks:
      - web3

#  eureka-server:
#    image: eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - 8761:8761
#    networks:
#      - web3
#    environment:
#      eureka.instance.hostname: eureka-server
#      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - web3
