server:
  port: 8085
  servlet:
    context-path: /financial-transactions
spring:
  application:
    name: financial-transactions
  config:
      import: 'optional:configserver:'
  cloud:
    config:
      fail-fast: true
      enabled: true
    uri: http://localhost:8888