server:
  port: 8085
  servlet:
    context-path: /financial-transactions

spring:
  application:
    name: financial-transactions

  cloud:
    config:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sa
    url: jdbc:postgresql://localhost:5433/bankdb

  jpa:
    format-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 10

  data:
    mongodb:
      uri: mongodb://localhost:27018/actiondb

  liquibase:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

rabbitmq:
  exchange_card:
    name: amq.direct
  queue_request_for_get_card:
    name: request_get_card
  queue_response_for_get_card:
    name: response_get_card
  queue_request_for_transfer:
    name: request_transfer
  queue_response_for_transfer:
    name: response_transfer
  queue_request_for_payment:
    name: request_payment
  queue_response_for_payment:
    name: response_payment
  routing_for_request_get_card:
    key: request_get_card
  routing_for_request_transfer:
    key: request_transfer
  routing_for_request_payment:
    key: request_payment

permissions:
  permission_for_transfer: transferMoneyBetweenYourAccounts
  permission_for_get_client_card: viewMyCards
  permission_for_payment: executionOfPayments

jwt:
  secret-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  expiration: 3600000